services:
  bank-backend:
    image: bank-backend-image
    build: banking/backend
    container_name: banking-backend
    ports:
      - "8000:8000"
    #env_file:
    #- .env
    volumes:
      - .:/app
    restart: "no"
  bank-frontend:
    image: bank-frontend-image
    build: banking/frontend/react-code
    container_name: banking-frontend
    ports:
      - "3000:5173"
    #env_file:
    #- .env
    volumes:
      - ./banking/frontend/react-code/src:/app/src
    restart: "no"
    command: npm run dev -- --host 0.0.0.0
